# fly.toml app configuration file generated for musicollmeet on 2023-05-03T16:19:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "musicollmeet"
primary_region = "cdg"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
