################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}/

####  MOMERS ####

### Liste des momers

GET {{endpoint}}momers

### Liste pour 1 momer

GET {{endpoint}}momers/1

### Modifier un momer
PATCH {{ endpoint }}momers/1
content-type: application/json

{
    "name": "name3",
    "picture_url": "picture_url3",
    "city":"city3",
    "email":"email3@email3.fr",
    "password":"password3",
    "phone":"0303030303",
    "address":"address3",
    "county":"county3",
    "description":"description3",
    "external_url": "external_url3",
    "momer_to_contact":"momer3",
    "momer_type_id": 2
}

#### MUSICOS ####

### liste des musicos
GET {{endpoint}}musicos

### liste pour 1 musicos
GET {{endpoint}}musicos/3

### Modifier un musicos

PATCH {{ endpoint }}musicos/3
content-type: application/json

{
    "name": "name3",
    "picture_url": "picture_url3",
    "city":"city3",
    "email":"email4@email4.fr",
    "password":"password3",
    "phone":"0303030303",
    "address":"address3",
    "county":"county3",
    "description":"description3",
    "external_url": "external_url3",
    "musicians_number": 4,
    "group_leader": "test3",
    "musical_type": [3,5]
}

#### EVENT PUBLIE ####

### LIste des events publiés

GET {{endpoint}}

### Liste de 1 event

GET {{endpoint}}2



#### ANNONCE ####

### Récupérer la liste des annonces

GET {{endpoint}}ads

### Récupérer 1 annonce

GET {{endpoint}}ads/1







